name: Release

on:
  push:
    branches:
      - main

env:
  BASE_BRANCH: 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-yarn
        name: Setup

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create PR or Publish
        id: release
        uses: changesets/action@v1
        with:
          title: |
            chore: version packages ${{ env.BASE_BRANCH }}
          commit: 'chore: version packages'
          version: yarn changeset version
          publish: yarn publish
        env:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}